package service;

import dao.HolidayDAO;
import model.Holiday;
import model.HolidayRule;
import util.LunarCalendarConverter;

import java.sql.Date;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class HolidayGeneratorService {

    private final HolidayDAO holidayDAO = new HolidayDAO();

    public boolean generateHolidaysForYear(int year) {
        // Idempotency check: if AUTO records already exist for this year, do nothing.
        if (holidayDAO.existsAutoGeneratedForYear(year)) {
            return false;
        }

        List<HolidayRule> rules = holidayDAO.getAllActiveRules();
        List<Holiday> holidaysToInsert = new ArrayList<>();
        Set<LocalDate> holidayDates = new HashSet<>();

        // Generate base holidays
        for (HolidayRule rule : rules) {
            LocalDate date = calculateDateForRule(rule, year);
            if (date != null) {
                Holiday h = new Holiday();
                h.setHolidayName(rule.getRuleName());
                h.setHolidayDate(Date.valueOf(date));
                h.setHolidayYear(year);
                h.setRuleCode(rule.getRuleCode());
                h.setSource("AUTO");
                h.setMakeupDay(false);
                h.setCalendarType(rule.getCalendarType());
                h.setOtMultiplier(rule.getOtMultiplier());
                h.setDescription("Tự động sinh từ cấu hình: " + rule.getRuleName());
                h.setStatus(true);
                
                holidaysToInsert.add(h);
                holidayDates.add(date);
            }
        }

        // Process makeup days for weekends
        List<Holiday> makeupHolidays = new ArrayList<>();
        for (Holiday h : holidaysToInsert) {
            LocalDate date = h.getHolidayDate().toLocalDate();
            DayOfWeek dayOfWeek = date.getDayOfWeek();
            
            if (dayOfWeek == DayOfWeek.SATURDAY || dayOfWeek == DayOfWeek.SUNDAY) {
                LocalDate makeupDate = date;
                // Find next available working day (not weekend, not already a holiday)
                do {
                    makeupDate = makeupDate.plusDays(1);
                } while (makeupDate.getDayOfWeek() == DayOfWeek.SATURDAY || 
                         makeupDate.getDayOfWeek() == DayOfWeek.SUNDAY || 
                         holidayDates.contains(makeupDate));
                
                Holiday makeup = new Holiday();
                makeup.setHolidayName(h.getHolidayName() + " (nghỉ bù)");
                makeup.setHolidayDate(Date.valueOf(makeupDate));
                makeup.setHolidayYear(year);
                makeup.setRuleCode(h.getRuleCode());
                makeup.setSource("AUTO");
                makeup.setMakeupDay(true);
                makeup.setCalendarType(h.getCalendarType());
                makeup.setOtMultiplier(h.getOtMultiplier());
                makeup.setDescription("Nghỉ bù cho " + h.getHolidayName() + " rơi vào cuối tuần.");
                makeup.setStatus(true);
                
                makeupHolidays.add(makeup);
                holidayDates.add(makeupDate); // So another makeup day doesn't land on this one
            }
        }
        
        holidaysToInsert.addAll(makeupHolidays);

        // Fetch existing MANUAL holidays to avoid duplicate insertion on same date
        List<Holiday> existingHolidays = holidayDAO.getByYear(year);
        Set<LocalDate> existingDates = new HashSet<>();
        for (Holiday ex : existingHolidays) {
            if ("MANUAL".equals(ex.getSource())) {
                existingDates.add(ex.getHolidayDate().toLocalDate());
            }
        }

        // Filter out those that conflict with MANUAL overrides
        List<Holiday> finalHolidaysToInsert = new ArrayList<>();
        for (Holiday h : holidaysToInsert) {
            if (!existingDates.contains(h.getHolidayDate().toLocalDate())) {
                finalHolidaysToInsert.add(h);
            }
        }

        holidayDAO.bulkInsert(finalHolidaysToInsert);
        return true;
    }

    private LocalDate calculateDateForRule(HolidayRule rule, int year) {
        if ("SOLAR".equals(rule.getCalendarType())) {
            LocalDate date = LocalDate.of(year, rule.getRefMonth(), rule.getRefDay());
            if (rule.getDayOffset() != 0) {
                date = date.plusDays(rule.getDayOffset());
            }
            return date;
        } else if ("LUNAR".equals(rule.getCalendarType())) {
            // For Lunar, we find the solar date for the given lunar day/month/year
            // Note: If rule is relative to Tet (Lunar 1/1), e.g., 29 Tet, we calculate 1/1 and subtract days.
            int[] solarDate;
            if (rule.getRefMonth() == 1 && rule.getRefDay() == 1) {
                // TET references
                solarDate = LunarCalendarConverter.convertLunar2Solar(1, 1, year, 0);
            } else {
                solarDate = LunarCalendarConverter.convertLunar2Solar(rule.getRefDay(), rule.getRefMonth(), year, 0);
            }
            
            LocalDate date = LocalDate.of(solarDate[2], solarDate[1], solarDate[0]);
            if (rule.getDayOffset() != 0) {
                date = date.plusDays(rule.getDayOffset());
            }
            return date;
        }
        return null;
    }
}
